# This file was generated by GoReleaser. DO NOT EDIT.
cask "juvenate" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "c845fe63c1b8e432cb1f792f62be453f4bada1ae72d400f93d3d35751c07b55e"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b30b112301fd7d25afaeb6a0d04a929a43e48c5bd6ff97b1d04e0e45919e24b4"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1abc9b94221274fd45ba2dcf3e1c06c63c4104a59ac34565ac6d8ae28d2fd6d5"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "079d33e83f2ffa636e68da74fcb8fb398d381384ada1ad0614501d4f9c6eaa51"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "juvenate"
  desc "Fast, lean dependency updates for GitOps repositories (Renovate-compatible)"
  homepage "https://github.com/mogenius/juvenate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "juvenate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/juvenate"]
    end
  end

  # No zap stanza required
end
