# This file was generated by GoReleaser. DO NOT EDIT.
cask "juvenate" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "865b60c76d9b36bffd4cbd5db0473a9892834d298bb9810337708f9e2b7b32b7"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7574fa94d8861b7a5f6f8c4eb40d81564a2eb1f4ec8376f66928e6d188b4a1bb"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa849316f05ae48e4bba85d5530a0b0eb87abf276bb24e1302b234db8c2105ea"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "013df6774120ee9c2a928f461e619b554ebeaf6069d99e6a995dc61b337f72a2"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "juvenate"
  desc "Fast, lean dependency updates for GitOps repositories (Renovate-compatible)"
  homepage "https://github.com/mogenius/juvenate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "juvenate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/juvenate"]
    end
  end

  # No zap stanza required
end
