# This file was generated by GoReleaser. DO NOT EDIT.
cask "juvenate" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "6b9401891120ce81a5341da6b90ebdf9d6059d69dd85271b43ffea6f0ec71ec3"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b1617a8401035c4f36ac3c636bdd217d9c5fd698e672d85b5d3fb377dfdb2757"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4327346c452d279489fc98ddb79f241775cf12537484fa5dd238fd0e59f33ea1"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2f469bd98fdfbf0722559caa8ce30ae1d39c0811f001d394fa2a836ea492286"
      url "https://github.com/mogenius/juvenate/releases/download/v#{version}/juvenate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "juvenate"
  desc "Fast, lean dependency updates for GitOps repositories (Renovate-compatible)"
  homepage "https://github.com/mogenius/juvenate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "juvenate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/juvenate"]
    end
  end

  # No zap stanza required
end
